from esphome.const import (
    CONF_UNIT_OF_MEASUREMENT,
    CONF_DEVICE_CLASS,
    CONF_STATE_CLASS,
    CONF_ACCURACY_DECIMALS,
    CONF_ICON,
)
from .const import (
    CONF_PID,
    CONF_MODE,
    CONF_FORMULA,
)


OBD_PRESETS = {
    # ── Engine ───────────────────────────────────────────────────────────────
    "engine_load": {
        CONF_MODE: "01",
        CONF_PID: "04",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:engine",
    },
    "coolant_temp": {
        CONF_MODE: "01",
        CONF_PID: "05",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:coolant-temperature",
    },
    "short_term_fuel_trim_b1": {
        CONF_MODE: "01",
        CONF_PID: "06",
        CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "long_term_fuel_trim_b1": {
        CONF_MODE: "01",
        CONF_PID: "07",
        CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "short_term_fuel_trim_b2": {
        CONF_MODE: "01",
        CONF_PID: "08",
        CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "long_term_fuel_trim_b2": {
        CONF_MODE: "01",
        CONF_PID: "09",
        CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "fuel_pressure": {
        CONF_MODE: "01",
        CONF_PID: "0A",
        CONF_FORMULA: "return a * 3.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "intake_pressure": {
        CONF_MODE: "01",
        CONF_PID: "0B",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "rpm": {
        CONF_MODE: "01",
        CONF_PID: "0C",
        CONF_FORMULA: "return (a * 256.0f + b) / 4.0f;",
        CONF_UNIT_OF_MEASUREMENT: "rpm",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:gauge",
    },
    "speed": {
        CONF_MODE: "01",
        CONF_PID: "0D",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "km/h",
        CONF_DEVICE_CLASS: "speed",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:speedometer",
    },
    "timing_advance": {
        CONF_MODE: "01",
        CONF_PID: "0E",
        CONF_FORMULA: "return a / 2.0f - 64.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:sine-wave",
    },
    "intake_air_temp": {
        CONF_MODE: "01",
        CONF_PID: "0F",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "maf": {
        CONF_MODE: "01",
        CONF_PID: "10",
        CONF_FORMULA: "return (a * 256.0f + b) / 100.0f;",
        CONF_UNIT_OF_MEASUREMENT: "g/s",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
        CONF_ICON: "mdi:weather-windy",
    },
    "throttle": {
        CONF_MODE: "01",
        CONF_PID: "11",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "o2_sensor_b1s1_voltage": {
        CONF_MODE: "01",
        CONF_PID: "14",
        CONF_FORMULA: "return a / 200.0f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 3,
    },
    "o2_sensor_b1s2_voltage": {
        CONF_MODE: "01",
        CONF_PID: "15",
        CONF_FORMULA: "return a / 200.0f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 3,
    },
    "o2_sensor_b2s1_voltage": {
        CONF_MODE: "01",
        CONF_PID: "18",
        CONF_FORMULA: "return a / 200.0f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 3,
    },
    "o2_sensor_b2s2_voltage": {
        CONF_MODE: "01",
        CONF_PID: "19",
        CONF_FORMULA: "return a / 200.0f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 3,
    },
    "run_time": {
        CONF_MODE: "01",
        CONF_PID: "1F",
        CONF_FORMULA: "return a * 256.0f + b;",
        CONF_UNIT_OF_MEASUREMENT: "s",
        CONF_DEVICE_CLASS: "duration",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 0,
    },
    # ── Distance / Diagnostic ─────────────────────────────────────────────────
    "distance_with_mil": {
        CONF_MODE: "01",
        CONF_PID: "21",
        CONF_FORMULA: "return a * 256.0f + b;",
        CONF_UNIT_OF_MEASUREMENT: "km",
        CONF_DEVICE_CLASS: "distance",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "fuel_rail_pressure": {
        CONF_MODE: "01",
        CONF_PID: "22",
        CONF_FORMULA: "return 0.079f * (a * 256.0f + b);",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "commanded_egr": {
        CONF_MODE: "01",
        CONF_PID: "2C",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "commanded_evap_purge": {
        CONF_MODE: "01",
        CONF_PID: "2E",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "fuel_level": {
        CONF_MODE: "01",
        CONF_PID: "2F",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gas-station",
    },
    "distance_since_cleared": {
        CONF_MODE: "01",
        CONF_PID: "31",
        CONF_FORMULA: "return a * 256.0f + b;",
        CONF_UNIT_OF_MEASUREMENT: "km",
        CONF_DEVICE_CLASS: "distance",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "evap_vapor_pressure": {
        CONF_MODE: "01",
        CONF_PID: "32",
        CONF_FORMULA: "return ((int16_t)((a << 8) | b)) / 4000.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 3,
    },
    "barometric": {
        CONF_MODE: "01",
        CONF_PID: "33",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "hPa",
        CONF_DEVICE_CLASS: "atmospheric_pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "catalyst_temp_b1s1": {
        CONF_MODE: "01",
        CONF_PID: "3C",
        CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:coolant-temperature",
    },
    "catalyst_temp_b2s1": {
        CONF_MODE: "01",
        CONF_PID: "3D",
        CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:coolant-temperature",
    },
    "catalyst_temp_b1s2": {
        CONF_MODE: "01",
        CONF_PID: "3E",
        CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:coolant-temperature",
    },
    "catalyst_temp_b2s2": {
        CONF_MODE: "01",
        CONF_PID: "3F",
        CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:coolant-temperature",
    },
    # ── Module / Throttle / Load ──────────────────────────────────────────────
    "battery_voltage": {
        CONF_MODE: "01",
        CONF_PID: "42",
        CONF_FORMULA: "return (a * 256.0f + b) / 1000.0f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "absolute_load": {
        CONF_MODE: "01",
        CONF_PID: "43",
        CONF_FORMULA: "return (a * 256.0f + b) * 100.0f / 255.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "commanded_afr": {
        CONF_MODE: "01",
        CONF_PID: "44",
        CONF_FORMULA: "return 2.0f * (a * 256.0f + b) / 65536.0f;",
        CONF_UNIT_OF_MEASUREMENT: "",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 3,
        CONF_ICON: "mdi:gauge",
    },
    "relative_throttle": {
        CONF_MODE: "01",
        CONF_PID: "45",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "ambient_temp": {
        CONF_MODE: "01",
        CONF_PID: "46",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "absolute_throttle_b": {
        CONF_MODE: "01",
        CONF_PID: "47",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "absolute_throttle_c": {
        CONF_MODE: "01",
        CONF_PID: "48",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "accel_pedal_d": {
        CONF_MODE: "01",
        CONF_PID: "49",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "accel_pedal_e": {
        CONF_MODE: "01",
        CONF_PID: "4A",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "throttle_actuator_ctrl": {
        CONF_MODE: "01",
        CONF_PID: "4C",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "time_with_mil": {
        CONF_MODE: "01",
        CONF_PID: "4D",
        CONF_FORMULA: "return a * 256.0f + b;",
        CONF_UNIT_OF_MEASUREMENT: "min",
        CONF_DEVICE_CLASS: "duration",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "time_since_cleared": {
        CONF_MODE: "01",
        CONF_PID: "4E",
        CONF_FORMULA: "return a * 256.0f + b;",
        CONF_UNIT_OF_MEASUREMENT: "min",
        CONF_DEVICE_CLASS: "duration",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "ethanol_percent": {
        CONF_MODE: "01",
        CONF_PID: "52",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:flask",
    },
    "absolute_evap_vapor_pressure": {
        CONF_MODE: "01",
        CONF_PID: "53",
        CONF_FORMULA: "return (a * 256.0f + b) / 200.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "evap_vapor_pressure_wide": {
        CONF_MODE: "01",
        CONF_PID: "54",
        CONF_FORMULA: "return ((int16_t)((a << 8) | b)) / 1000.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 3,
    },
    "fuel_rail_pressure_abs": {
        CONF_MODE: "01",
        CONF_PID: "59",
        CONF_FORMULA: "return (a * 256.0f + b) * 10.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "relative_accel_pedal": {
        CONF_MODE: "01",
        CONF_PID: "5A",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "hybrid_battery": {
        CONF_MODE: "01",
        CONF_PID: "5B",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_DEVICE_CLASS: "battery",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "oil_temp": {
        CONF_MODE: "01",
        CONF_PID: "5C",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:oil-temperature",
    },
    "fuel_injection_timing": {
        CONF_MODE: "01",
        CONF_PID: "5D",
        CONF_FORMULA: "return (a * 256.0f + b) / 128.0f - 210.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
        CONF_ICON: "mdi:sine-wave",
    },
    "fuel_rate": {
        CONF_MODE: "01",
        CONF_PID: "5E",
        CONF_FORMULA: "return (a * 256.0f + b) / 20.0f;",
        CONF_UNIT_OF_MEASUREMENT: "L/h",
        CONF_DEVICE_CLASS: "volume_flow_rate",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
        CONF_ICON: "mdi:gas-station",
    },
    # ── Torque ───────────────────────────────────────────────────────────────
    "demand_torque": {
        CONF_MODE: "01",
        CONF_PID: "61",
        CONF_FORMULA: "return a - 125.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:gauge",
    },
    "actual_torque": {
        CONF_MODE: "01",
        CONF_PID: "62",
        CONF_FORMULA: "return a - 125.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:gauge",
    },
    "ref_torque": {
        CONF_MODE: "01",
        CONF_PID: "63",
        CONF_FORMULA: "return a * 256.0f + b;",
        CONF_UNIT_OF_MEASUREMENT: "N·m",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:gauge",
    },
    # ── Extended PIDs (SAE J1979) ─────────────────────────────────────────────
    "maf_sensor_a": {
        CONF_MODE: "01",
        CONF_PID: "66",
        CONF_FORMULA: "return (a * 256.0f + b) / 32.0f;",
        CONF_UNIT_OF_MEASUREMENT: "g/s",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
        CONF_ICON: "mdi:weather-windy",
    },
    "maf_sensor_b": {
        CONF_MODE: "01",
        CONF_PID: "66",
        CONF_FORMULA: "return (c * 256.0f + d) / 32.0f;",
        CONF_UNIT_OF_MEASUREMENT: "g/s",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
        CONF_ICON: "mdi:weather-windy",
    },
    "coolant_temp_sensor_1": {
        CONF_MODE: "01",
        CONF_PID: "67",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:coolant-temperature",
    },
    "coolant_temp_sensor_2": {
        CONF_MODE: "01",
        CONF_PID: "67",
        CONF_FORMULA: "return b - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:coolant-temperature",
    },
    "intake_temp_sensor_1": {
        CONF_MODE: "01",
        CONF_PID: "68",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "intake_temp_sensor_2": {
        CONF_MODE: "01",
        CONF_PID: "68",
        CONF_FORMULA: "return b - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "egr_a_cmd": {
        CONF_MODE: "01",
        CONF_PID: "69",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "egr_a_act": {
        CONF_MODE: "01",
        CONF_PID: "69",
        CONF_FORMULA: "return b / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "egr_a_err": {
        CONF_MODE: "01",
        CONF_PID: "69",
        CONF_FORMULA: "return (c * 100.0f / 128.0f) - 100.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "egr_b_cmd": {
        CONF_MODE: "01",
        CONF_PID: "69",
        CONF_FORMULA: "return d / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "egr_temp_sensor_a": {
        CONF_MODE: "01",
        CONF_PID: "6B",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "egr_temp_sensor_b": {
        CONF_MODE: "01",
        CONF_PID: "6B",
        CONF_FORMULA: "return b - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "egr_temp_sensor_c": {
        CONF_MODE: "01",
        CONF_PID: "6B",
        CONF_FORMULA: "return c - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "egr_temp_sensor_d": {
        CONF_MODE: "01",
        CONF_PID: "6B",
        CONF_FORMULA: "return d - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "throttle_actuator_a_cmd": {
        CONF_MODE: "01",
        CONF_PID: "6C",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "throttle_a_relative": {
        CONF_MODE: "01",
        CONF_PID: "6C",
        CONF_FORMULA: "return b / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "throttle_actuator_b_cmd": {
        CONF_MODE: "01",
        CONF_PID: "6C",
        CONF_FORMULA: "return c / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "throttle_b_relative": {
        CONF_MODE: "01",
        CONF_PID: "6C",
        CONF_FORMULA: "return d / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "commanded_boost_pressure_a": {
        CONF_MODE: "01",
        CONF_PID: "70",
        CONF_FORMULA: "return (a * 256.0f + b) / 32.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "boost_pressure_sensor_a": {
        CONF_MODE: "01",
        CONF_PID: "70",
        CONF_FORMULA: "return (c * 256.0f + d) / 32.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kPa",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "commanded_wastegate_a": {
        CONF_MODE: "01",
        CONF_PID: "72",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "wastegate_a_actual": {
        CONF_MODE: "01",
        CONF_PID: "72",
        CONF_FORMULA: "return b / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "commanded_wastegate_b": {
        CONF_MODE: "01",
        CONF_PID: "72",
        CONF_FORMULA: "return c / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "wastegate_b_actual": {
        CONF_MODE: "01",
        CONF_PID: "72",
        CONF_FORMULA: "return d / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "total_engine_run_time": {
        CONF_MODE: "01",
        CONF_PID: "7F",
        CONF_FORMULA: "uint32_t v = ((uint32_t)a << 24) | ((uint32_t)b << 16) | ((uint32_t)c << 8) | d; return v;",
        CONF_UNIT_OF_MEASUREMENT: "s",
        CONF_DEVICE_CLASS: "duration",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "manifold_surface_temp": {
        CONF_MODE: "01",
        CONF_PID: "84",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "engine_friction_torque": {
        CONF_MODE: "01",
        CONF_PID: "8E",
        CONF_FORMULA: "return a - 125.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:gauge",
    },
    "hev_battery_voltage": {
        CONF_MODE: "01",
        CONF_PID: "9A",
        CONF_FORMULA: "return (((uint32_t)c << 8) | d) / 64.0f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "engine_fuel_rate_alt": {
        CONF_MODE: "01",
        CONF_PID: "9D",
        CONF_FORMULA: "return (a * 256.0f + b) / 50.0f;",
        CONF_UNIT_OF_MEASUREMENT: "g/s",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
        CONF_ICON: "mdi:gas-station",
    },
    "vehicle_fuel_rate": {
        CONF_MODE: "01",
        CONF_PID: "9D",
        CONF_FORMULA: "return (c * 256.0f + d) / 50.0f;",
        CONF_UNIT_OF_MEASUREMENT: "g/s",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
        CONF_ICON: "mdi:gas-station",
    },
    "exhaust_flow_rate": {
        CONF_MODE: "01",
        CONF_PID: "9E",
        CONF_FORMULA: "return (a * 256.0f + b) / 5.0f;",
        CONF_UNIT_OF_MEASUREMENT: "kg/h",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:weather-windy",
    },
    "fuel_system_a_use_b1": {
        CONF_MODE: "01",
        CONF_PID: "9F",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "fuel_system_b_use_b1": {
        CONF_MODE: "01",
        CONF_PID: "9F",
        CONF_FORMULA: "return b / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "fuel_system_a_use_b2": {
        CONF_MODE: "01",
        CONF_PID: "9F",
        CONF_FORMULA: "return c / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "fuel_system_b_use_b2": {
        CONF_MODE: "01",
        CONF_PID: "9F",
        CONF_FORMULA: "return d / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "odometer": {
        CONF_MODE: "01",
        CONF_PID: "A6",
        CONF_FORMULA: "uint32_t v = ((uint32_t)a << 24) | ((uint32_t)b << 16) | ((uint32_t)c << 8) | d; return v / 10.0f;",
        CONF_UNIT_OF_MEASUREMENT: "km",
        CONF_DEVICE_CLASS: "distance",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "vehicle_speed_limit": {
        CONF_MODE: "01",
        CONF_PID: "AA",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "km/h",
        CONF_DEVICE_CLASS: "speed",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
    },
    "traction_battery_soh": {
        CONF_MODE: "01",
        CONF_PID: "B2",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:battery-heart-variant",
    },
    "state_of_certified_energy": {
        CONF_MODE: "01",
        CONF_PID: "D2",
        CONF_FORMULA: "return b / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "state_of_certified_range": {
        CONF_MODE: "01",
        CONF_PID: "D2",
        CONF_FORMULA: "return c / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "engine_odometer": {
        CONF_MODE: "01",
        CONF_PID: "D3",
        CONF_FORMULA: "uint32_t v = ((uint32_t)a << 24) | ((uint32_t)b << 16) | ((uint32_t)c << 8) | d; return v / 10.0f;",
        CONF_UNIT_OF_MEASUREMENT: "km",
        CONF_DEVICE_CLASS: "distance",
        CONF_STATE_CLASS: "total_increasing",
        CONF_ACCURACY_DECIMALS: 1,
    },
    # ── GM Specific (Mode 22) ────────────────────────────────────────────────
    "gm_ect_volts": {
        CONF_MODE: "22",
        CONF_PID: "1149",
        CONF_FORMULA: "return a * 0.02f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "gm_iat_volts": {
        CONF_MODE: "22",
        CONF_PID: "114B",
        CONF_FORMULA: "return a * 0.02f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "gm_oil_temp": {
        CONF_MODE: "22",
        CONF_PID: "1154",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:oil-temperature",
    },
    "gm_fuel_level_volts": {
        CONF_MODE: "22",
        CONF_PID: "1155",
        CONF_FORMULA: "return a * 0.02f;",
        CONF_UNIT_OF_MEASUREMENT: "V",
        CONF_DEVICE_CLASS: "voltage",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "gm_fuel_level": {
        CONF_MODE: "22",
        CONF_PID: "111D",
        CONF_FORMULA: "return a * 100.0f / 255.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gas-station",
    },
    "gm_oil_pressure": {
        CONF_MODE: "22",
        CONF_PID: "115C",
        CONF_FORMULA: "return (a * 0.65f) - 17.5f;",
        CONF_UNIT_OF_MEASUREMENT: "psi",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "gm_fuel_trim_cell": {
        CONF_MODE: "22",
        CONF_PID: "1160",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:numeric",
    },
    "gm_fuel_injector_pw": {
        CONF_MODE: "22",
        CONF_PID: "119B",
        CONF_FORMULA: "return (a * 256.0f + b) * 0.001f;",
        CONF_UNIT_OF_MEASUREMENT: "ms",
        CONF_DEVICE_CLASS: "duration",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 2,
    },
    "gm_fuel_pump_duty": {
        CONF_MODE: "22",
        CONF_PID: "119C",
        CONF_FORMULA: "return a * 0.392f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gas-station",
    },
    "gm_oil_life": {
        CONF_MODE: "22",
        CONF_PID: "119F",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:oil",
    },
    "gm_oil_life_alt": {
        CONF_MODE: "22",
        CONF_PID: "1151",
        CONF_FORMULA: "return a * 100.0f / 255.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:oil",
    },
    "gm_oil_life_alt2": {
        CONF_MODE: "22",
        CONF_PID: "119E",
        CONF_FORMULA: "return a * 100.0f / 255.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:oil",
    },
    "gm_battery_current": {
        CONF_MODE: "22",
        CONF_PID: "1173",
        CONF_FORMULA: "return ((int16_t)((a << 8) | b)) / 10.0f;",
        CONF_UNIT_OF_MEASUREMENT: "A",
        CONF_DEVICE_CLASS: "current",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
    },
    "gm_battery_temp": {
        CONF_MODE: "22",
        CONF_PID: "1163",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:thermometer",
    },
    "gm_battery_soc": {
        CONF_MODE: "22",
        CONF_PID: "4028",
        CONF_FORMULA: "return a * 100.0f / 255.0f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:battery-charging",
    },
    "gm_knock_retard": {
        CONF_MODE: "22",
        CONF_PID: "11A6",
        CONF_FORMULA: "return a * 0.0878906f;",
        CONF_UNIT_OF_MEASUREMENT: "°",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:sine-wave",
    },
    "gm_fan_duty": {
        CONF_MODE: "22",
        CONF_PID: "162B",
        CONF_FORMULA: "return a / 2.55f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:fan",
    },
    "gm_trans_temp": {
        CONF_MODE: "22",
        CONF_PID: "1940",
        CONF_FORMULA: "return a - 40.0f;",
        CONF_UNIT_OF_MEASUREMENT: "°C",
        CONF_DEVICE_CLASS: "temperature",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:oil-temperature",
    },
    "gm_tcc_slip": {
        CONF_MODE: "22",
        CONF_PID: "1991",
        CONF_FORMULA: "return ((int16_t)((a << 8) | b)) / 8.0f;",
        CONF_UNIT_OF_MEASUREMENT: "rpm",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "gm_tcc_slip_speed": {
        CONF_MODE: "22",
        CONF_PID: "1941",
        CONF_FORMULA: "return a * 256.0f + b;",
        CONF_UNIT_OF_MEASUREMENT: "rpm",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:gauge",
    },
    "gm_tcc_duty_cycle": {
        CONF_MODE: "22",
        CONF_PID: "192A",
        CONF_FORMULA: "return a * 0.392f;",
        CONF_UNIT_OF_MEASUREMENT: "%",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:gauge",
    },
    "gm_current_gear": {
        CONF_MODE: "22",
        CONF_PID: "199A",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:car-shift-pattern",
    },
    "gm_prnd_status": {
        CONF_MODE: "22",
        CONF_PID: "1951",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:car-shift-pattern",
    },
    "gm_prnd_status_alt": {
        CONF_MODE: "22",
        CONF_PID: "2889",
        CONF_FORMULA: "return a;",
        CONF_UNIT_OF_MEASUREMENT: "",
        CONF_ACCURACY_DECIMALS: 0,
        CONF_ICON: "mdi:car-shift-pattern",
    },
    "gm_tpms_lf": {
        CONF_MODE: "22",
        CONF_PID: "2813",
        CONF_FORMULA: "return a * 0.145f;",
        CONF_UNIT_OF_MEASUREMENT: "psi",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:tire",
    },
    "gm_tpms_rf": {
        CONF_MODE: "22",
        CONF_PID: "2814",
        CONF_FORMULA: "return a * 0.145f;",
        CONF_UNIT_OF_MEASUREMENT: "psi",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:tire",
    },
    "gm_tpms_lr": {
        CONF_MODE: "22",
        CONF_PID: "2815",
        CONF_FORMULA: "return a * 0.145f;",
        CONF_UNIT_OF_MEASUREMENT: "psi",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:tire",
    },
    "gm_tpms_rr": {
        CONF_MODE: "22",
        CONF_PID: "2816",
        CONF_FORMULA: "return a * 0.145f;",
        CONF_UNIT_OF_MEASUREMENT: "psi",
        CONF_DEVICE_CLASS: "pressure",
        CONF_STATE_CLASS: "measurement",
        CONF_ACCURACY_DECIMALS: 1,
        CONF_ICON: "mdi:tire",
    },
}


