from esphome.const import (
    CONF_UNIT_OF_MEASUREMENT, CONF_DEVICE_CLASS, CONF_STATE_CLASS, CONF_ACCURACY_DECIMALS,
)
from .const import CONF_PID, CONF_MODE, CONF_FORMULA

OBD_PRESETS = {
    # ── Engine ───────────────────────────────────────────────────────────────
    "engine_load":              {CONF_PID: "04", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "coolant_temp":             {CONF_PID: "05", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "short_term_fuel_trim_b1":  {CONF_PID: "06", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "long_term_fuel_trim_b1":   {CONF_PID: "07", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "short_term_fuel_trim_b2":  {CONF_PID: "08", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "long_term_fuel_trim_b2":   {CONF_PID: "09", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 100.0f / 128.0f) - 100.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "fuel_pressure":            {CONF_PID: "0A", CONF_MODE: "01",
                                 CONF_FORMULA: "return a * 3.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "intake_pressure":          {CONF_PID: "0B", CONF_MODE: "01",
                                 CONF_FORMULA: "return a;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_DEVICE_CLASS: "pressure", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "rpm":                      {CONF_PID: "0C", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 4.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "rpm",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "speed":                    {CONF_PID: "0D", CONF_MODE: "01",
                                 CONF_FORMULA: "return a;",
                                 CONF_UNIT_OF_MEASUREMENT: "km/h", CONF_DEVICE_CLASS: "speed", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "timing_advance":           {CONF_PID: "0E", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.0f - 64.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "intake_air_temp":          {CONF_PID: "0F", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "maf":                      {CONF_PID: "10", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 100.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "g/s",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "throttle":                 {CONF_PID: "11", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "o2_sensor_b1s1_voltage":   {CONF_PID: "14", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 200.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 3},
    "o2_sensor_b1s2_voltage":   {CONF_PID: "15", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 200.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 3},
    "o2_sensor_b2s1_voltage":   {CONF_PID: "18", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 200.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 3},
    "o2_sensor_b2s2_voltage":   {CONF_PID: "19", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 200.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 3},
    "run_time":                 {CONF_PID: "1F", CONF_MODE: "01",
                                 CONF_FORMULA: "return a * 256.0f + b;",
                                 CONF_UNIT_OF_MEASUREMENT: "s",    CONF_DEVICE_CLASS: "duration", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 0},
    # ── Distance / Diagnostic ─────────────────────────────────────────────────
    "distance_with_mil":        {CONF_PID: "21", CONF_MODE: "01",
                                 CONF_FORMULA: "return a * 256.0f + b;",
                                 CONF_UNIT_OF_MEASUREMENT: "km",   CONF_DEVICE_CLASS: "distance", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 0},
    "fuel_rail_pressure":       {CONF_PID: "22", CONF_MODE: "01",
                                 CONF_FORMULA: "return 0.079f * (a * 256.0f + b);",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "commanded_egr":            {CONF_PID: "2C", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "commanded_evap_purge":     {CONF_PID: "2E", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "fuel_level":               {CONF_PID: "2F", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_DEVICE_CLASS: "battery", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "distance_since_cleared":   {CONF_PID: "31", CONF_MODE: "01",
                                 CONF_FORMULA: "return a * 256.0f + b;",
                                 CONF_UNIT_OF_MEASUREMENT: "km",   CONF_DEVICE_CLASS: "distance", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 0},
    "evap_vapor_pressure":      {CONF_PID: "32", CONF_MODE: "01",
                                 CONF_FORMULA: "return ((int16_t)((a << 8) | b)) / 4000.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 3},
    "barometric":               {CONF_PID: "33", CONF_MODE: "01",
                                 CONF_FORMULA: "return a;",
                                 CONF_UNIT_OF_MEASUREMENT: "hPa",  CONF_DEVICE_CLASS: "atmospheric_pressure", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "catalyst_temp_b1s1":       {CONF_PID: "3C", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "catalyst_temp_b2s1":       {CONF_PID: "3D", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "catalyst_temp_b1s2":       {CONF_PID: "3E", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "catalyst_temp_b2s2":       {CONF_PID: "3F", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 10.0f - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    # ── Module / Throttle / Load ──────────────────────────────────────────────
    "battery_voltage":          {CONF_PID: "42", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 1000.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "absolute_load":            {CONF_PID: "43", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) * 100.0f / 255.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "commanded_afr":            {CONF_PID: "44", CONF_MODE: "01",
                                 CONF_FORMULA: "return 2.0f * (a * 256.0f + b) / 65536.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "",     CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 3},
    "relative_throttle":        {CONF_PID: "45", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "ambient_temp":             {CONF_PID: "46", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "absolute_throttle_b":      {CONF_PID: "47", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "absolute_throttle_c":      {CONF_PID: "48", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "accel_pedal_d":            {CONF_PID: "49", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "accel_pedal_e":            {CONF_PID: "4A", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "throttle_actuator_ctrl":   {CONF_PID: "4C", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "time_with_mil":            {CONF_PID: "4D", CONF_MODE: "01",
                                 CONF_FORMULA: "return a * 256.0f + b;",
                                 CONF_UNIT_OF_MEASUREMENT: "min",  CONF_DEVICE_CLASS: "duration", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 0},
    "time_since_cleared":       {CONF_PID: "4E", CONF_MODE: "01",
                                 CONF_FORMULA: "return a * 256.0f + b;",
                                 CONF_UNIT_OF_MEASUREMENT: "min",  CONF_DEVICE_CLASS: "duration", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 0},
    "ethanol_percent":          {CONF_PID: "52", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "absolute_evap_vapor_pressure": {CONF_PID: "53", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 200.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "evap_vapor_pressure_wide": {CONF_PID: "54", CONF_MODE: "01",
                                 CONF_FORMULA: "return ((int16_t)((a << 8) | b)) / 1000.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 3},
    "fuel_rail_pressure_abs":   {CONF_PID: "59", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) * 10.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "relative_accel_pedal":     {CONF_PID: "5A", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "hybrid_battery":           {CONF_PID: "5B", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_DEVICE_CLASS: "battery", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "oil_temp":                 {CONF_PID: "5C", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "fuel_injection_timing":    {CONF_PID: "5D", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 128.0f - 210.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "fuel_rate":                {CONF_PID: "5E", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 20.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "L/h",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    # ── Torque ───────────────────────────────────────────────────────────────
    "demand_torque":            {CONF_PID: "61", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 125.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "actual_torque":            {CONF_PID: "62", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 125.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "ref_torque":               {CONF_PID: "63", CONF_MODE: "01",
                                 CONF_FORMULA: "return a * 256.0f + b;",
                                 CONF_UNIT_OF_MEASUREMENT: "N·m",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    # ── Extended PIDs (SAE J1979) ─────────────────────────────────────────────
    "maf_sensor_a":             {CONF_PID: "66", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 32.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "g/s",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "maf_sensor_b":             {CONF_PID: "66", CONF_MODE: "01",
                                 CONF_FORMULA: "return (c * 256.0f + d) / 32.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "g/s",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "coolant_temp_sensor_1":    {CONF_PID: "67", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "coolant_temp_sensor_2":    {CONF_PID: "67", CONF_MODE: "01",
                                 CONF_FORMULA: "return b - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "intake_temp_sensor_1":     {CONF_PID: "68", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "intake_temp_sensor_2":     {CONF_PID: "68", CONF_MODE: "01",
                                 CONF_FORMULA: "return b - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_a_cmd":                {CONF_PID: "69", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_a_act":                {CONF_PID: "69", CONF_MODE: "01",
                                 CONF_FORMULA: "return b / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_a_err":                {CONF_PID: "69", CONF_MODE: "01",
                                 CONF_FORMULA: "return (c * 100.0f / 128.0f) - 100.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_b_cmd":                {CONF_PID: "69", CONF_MODE: "01",
                                 CONF_FORMULA: "return d / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_temp_sensor_a":        {CONF_PID: "6B", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_temp_sensor_b":        {CONF_PID: "6B", CONF_MODE: "01",
                                 CONF_FORMULA: "return b - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_temp_sensor_c":        {CONF_PID: "6B", CONF_MODE: "01",
                                 CONF_FORMULA: "return c - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "egr_temp_sensor_d":        {CONF_PID: "6B", CONF_MODE: "01",
                                 CONF_FORMULA: "return d - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "throttle_actuator_a_cmd":  {CONF_PID: "6C", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "throttle_a_relative":      {CONF_PID: "6C", CONF_MODE: "01",
                                 CONF_FORMULA: "return b / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "throttle_actuator_b_cmd":  {CONF_PID: "6C", CONF_MODE: "01",
                                 CONF_FORMULA: "return c / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "throttle_b_relative":      {CONF_PID: "6C", CONF_MODE: "01",
                                 CONF_FORMULA: "return d / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "commanded_boost_pressure_a": {CONF_PID: "70", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 32.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "boost_pressure_sensor_a":  {CONF_PID: "70", CONF_MODE: "01",
                                 CONF_FORMULA: "return (c * 256.0f + d) / 32.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kPa",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "commanded_wastegate_a":    {CONF_PID: "72", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "wastegate_a_actual":       {CONF_PID: "72", CONF_MODE: "01",
                                 CONF_FORMULA: "return b / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "commanded_wastegate_b":    {CONF_PID: "72", CONF_MODE: "01",
                                 CONF_FORMULA: "return c / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "wastegate_b_actual":       {CONF_PID: "72", CONF_MODE: "01",
                                 CONF_FORMULA: "return d / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "total_engine_run_time":    {CONF_PID: "7F", CONF_MODE: "01",
                                 CONF_FORMULA: "uint32_t v = ((uint32_t)a << 24) | ((uint32_t)b << 16) | ((uint32_t)c << 8) | d; return v;",
                                 CONF_UNIT_OF_MEASUREMENT: "s",    CONF_DEVICE_CLASS: "duration", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 0},
    "manifold_surface_temp":    {CONF_PID: "84", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "engine_friction_torque":   {CONF_PID: "8E", CONF_MODE: "01",
                                 CONF_FORMULA: "return a - 125.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "hev_battery_voltage":      {CONF_PID: "9A", CONF_MODE: "01",
                                 CONF_FORMULA: "return (((uint32_t)c << 8) | d) / 64.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "engine_fuel_rate_alt":     {CONF_PID: "9D", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 50.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "g/s",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "vehicle_fuel_rate":        {CONF_PID: "9D", CONF_MODE: "01",
                                 CONF_FORMULA: "return (c * 256.0f + d) / 50.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "g/s",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "exhaust_flow_rate":        {CONF_PID: "9E", CONF_MODE: "01",
                                 CONF_FORMULA: "return (a * 256.0f + b) / 5.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "kg/h", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "fuel_system_a_use_b1":     {CONF_PID: "9F", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "fuel_system_b_use_b1":     {CONF_PID: "9F", CONF_MODE: "01",
                                 CONF_FORMULA: "return b / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "fuel_system_a_use_b2":     {CONF_PID: "9F", CONF_MODE: "01",
                                 CONF_FORMULA: "return c / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "fuel_system_b_use_b2":     {CONF_PID: "9F", CONF_MODE: "01",
                                 CONF_FORMULA: "return d / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "odometer":                 {CONF_PID: "A6", CONF_MODE: "01",
                                 CONF_FORMULA: "uint32_t v = ((uint32_t)a << 24) | ((uint32_t)b << 16) | ((uint32_t)c << 8) | d; return v / 10.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "km",   CONF_DEVICE_CLASS: "distance", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 1},
    "vehicle_speed_limit":      {CONF_PID: "AA", CONF_MODE: "01",
                                 CONF_FORMULA: "return a;",
                                 CONF_UNIT_OF_MEASUREMENT: "km/h", CONF_DEVICE_CLASS: "speed", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "traction_battery_soh":     {CONF_PID: "B2", CONF_MODE: "01",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "state_of_certified_energy":{CONF_PID: "D2", CONF_MODE: "01",
                                 CONF_FORMULA: "return b / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "state_of_certified_range": {CONF_PID: "D2", CONF_MODE: "01",
                                 CONF_FORMULA: "return c / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "engine_odometer":          {CONF_PID: "D3", CONF_MODE: "01",
                                 CONF_FORMULA: "uint32_t v = ((uint32_t)a << 24) | ((uint32_t)b << 16) | ((uint32_t)c << 8) | d; return v / 10.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "km",   CONF_DEVICE_CLASS: "distance", CONF_STATE_CLASS: "total_increasing", CONF_ACCURACY_DECIMALS: 1},
    # ── GM Specific (Mode 22) ────────────────────────────────────────────────
    "gm_ect_volts":             {CONF_PID: "1149", CONF_MODE: "22",
                                 CONF_FORMULA: "return a * 0.02f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "gm_iat_volts":             {CONF_PID: "114B", CONF_MODE: "22",
                                 CONF_FORMULA: "return a * 0.02f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "gm_oil_temp":              {CONF_PID: "1154", CONF_MODE: "22",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "gm_fuel_level_volts":      {CONF_PID: "1155", CONF_MODE: "22",
                                 CONF_FORMULA: "return a * 0.02f;",
                                 CONF_UNIT_OF_MEASUREMENT: "V",    CONF_DEVICE_CLASS: "voltage", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "gm_oil_pressure":          {CONF_PID: "115C", CONF_MODE: "22",
                                 CONF_FORMULA: "return (a * 0.65f) - 17.5f;",
                                 CONF_UNIT_OF_MEASUREMENT: "psi",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "gm_fuel_trim_cell":        {CONF_PID: "1160", CONF_MODE: "22",
                                 CONF_FORMULA: "return a;",
                                 CONF_UNIT_OF_MEASUREMENT: "",     CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
    "gm_fuel_injector_pw":      {CONF_PID: "119B", CONF_MODE: "22",
                                 CONF_FORMULA: "return (a * 256.0f + b) * 0.001f;",
                                 CONF_UNIT_OF_MEASUREMENT: "ms",   CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 2},
    "gm_oil_life":              {CONF_PID: "119F", CONF_MODE: "22",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "gm_knock_retard":          {CONF_PID: "11A6", CONF_MODE: "22",
                                 CONF_FORMULA: "return a * 0.0878906f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "gm_fan_duty":              {CONF_PID: "162B", CONF_MODE: "22",
                                 CONF_FORMULA: "return a / 2.55f;",
                                 CONF_UNIT_OF_MEASUREMENT: "%",    CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "gm_trans_temp":            {CONF_PID: "1940", CONF_MODE: "22",
                                 CONF_FORMULA: "return a - 40.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "°C",   CONF_DEVICE_CLASS: "temperature", CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "gm_tcc_slip":              {CONF_PID: "1991", CONF_MODE: "22",
                                 CONF_FORMULA: "return ((int16_t)((a << 8) | b)) / 8.0f;",
                                 CONF_UNIT_OF_MEASUREMENT: "rpm",  CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 1},
    "gm_current_gear":          {CONF_PID: "199A", CONF_MODE: "22",
                                 CONF_FORMULA: "return a;",
                                 CONF_UNIT_OF_MEASUREMENT: "",     CONF_STATE_CLASS: "measurement", CONF_ACCURACY_DECIMALS: 0},
}
