# coding=utf-8
"""Constants used by esphome."""

CONF_RS485_ID = 'rs485_id'
CONF_DATA_BITS = 'data_bits'
CONF_PARITY = 'parity'
CONF_STOP_BITS = 'stop_bits'
CONF_RX_WAIT = 'rx_wait'
CONF_TX_INTERVAL = 'tx_interval'
CONF_TX_WAIT = 'tx_wait'
CONF_TX_RETRY_CNT = 'tx_retry_cnt'
CONF_CTRL_PIN = 'ctrl_pin'
CONF_PREFIX = 'prefix'
CONF_SUFFIX = 'suffix'
CONF_CHECKSUM = 'checksum'
CONF_CHECKSUM2 = 'checksum2'
CONF_CHECKSUM_LAMBDA = 'checksum_lambda'
CONF_SUB_DEVICE = 'sub_device'
CONF_AND_OPERATOR = 'and_operator'

CONF_STATE_ON = 'state_on'
CONF_STATE_OFF = 'state_off'
CONF_STATE_RESPONSE = 'state_response'
CONF_STATE_CURRENT = 'state_current'
CONF_STATE_TARGET = 'state_target'
CONF_STATE_AUTO = 'state_auto'
CONF_STATE_HEAT = 'state_heat'
CONF_STATE_COOL = 'state_cool'
CONF_STATE_AWAY = 'state_away'

CONF_COMMAND_STATE = 'command_state'
CONF_COMMAND_ON = 'command_on'
CONF_COMMAND_OFF = 'command_off'
CONF_COMMAND_TEMPERATURE = 'command_temperature'
CONF_COMMAND_AUTO = 'command_auto'
CONF_COMMAND_HEAT = 'command_heat'
CONF_COMMAND_COOL = 'command_cool'
CONF_COMMAND_AWAY = 'command_away'
CONF_COMMAND_HOME = 'command_home'

CONF_ACK = 'ack'
CONF_PACKET_MONITOR_ID = 'packet_monitor_id'
CONF_PACKET_MONITOR = 'packet_monitor'

CONF_LENGTH = 'length'
CONF_PRECISION = 'precision'
