# coding=utf-8
"""Constants used by esphome."""

CONF_BLUETOOTHEX_ID = 'bluetoothex_id'
CONF_DEVICE_NAME = "device_name"
CONF_RX_TIMEOUT = 'rx_timeout'
CONF_TX_DELAY = 'tx_delay'
CONF_TX_TIMEOUT = 'tx_timeout'
CONF_TX_RETRY_CNT = 'tx_retry_cnt'
CONF_TX_CTRL_PIN = 'tx_ctrl_pin'
CONF_RX_HEADER = 'rx_header'
CONF_RX_FOOTER = 'rx_footer'
CONF_TX_HEADER = 'tx_header'
CONF_TX_FOOTER = 'tx_footer'
CONF_RX_CHECKSUM = 'rx_checksum'
CONF_TX_CHECKSUM = 'tx_checksum'
CONF_RX_CHECKSUM_2 = 'rx_checksum2'
CONF_TX_CHECKSUM_2 = 'tx_checksum2'
CONF_MASK = 'mask'
CONF_ERROR = 'error'

CONF_FILTER = 'filter'
CONF_SUB_FILTER = 'sub_filter'
CONF_STATE_ON = 'state_on'
CONF_STATE_OFF = 'state_off'
CONF_STATE_NUMBER = 'state_number'
CONF_STATE_RESPONSE = 'state_response'
CONF_STATE_TEMPERATURE_CURRENT = 'state_temperature_current'
CONF_STATE_TEMPERATURE_TARGET = 'state_temperature_target'
CONF_STATE_AUTO = 'state_auto'
CONF_STATE_HEAT = 'state_heat'
CONF_STATE_COOL = 'state_cool'
CONF_STATE_AWAY = 'state_away'
CONF_STATE_LOCKED = 'state_locked'
CONF_STATE_UNLOCKED = 'state_unlocked'
CONF_STATE_JAMMED = 'state_jammed'
CONF_STATE_LOCKING = 'state_locking'
CONF_STATE_UNLOCKING = 'state_unlocking'
CONF_STATE_SPEED = 'state_speed'

CONF_COMMAND_UPDATE = 'command_update'
CONF_COMMAND_ON = 'command_on'
CONF_COMMAND_OFF = 'command_off'
CONF_COMMAND_TEMPERATURE = 'command_temperature'
CONF_COMMAND_AUTO = 'command_auto'
CONF_COMMAND_HEAT = 'command_heat'
CONF_COMMAND_COOL = 'command_cool'
CONF_COMMAND_AWAY = 'command_away'
CONF_COMMAND_HOME = 'command_home'
CONF_COMMAND_LOCK = 'command_lock'
CONF_COMMAND_UNLOCK = 'command_unlock'
CONF_COMMAND_NUMBER = 'command_number'
CONF_COMMAND_SPEED = 'command_speed'
CONF_ACK = 'ack'
CONF_LENGTH = 'length'
CONF_PRECISION = 'precision'
CONF_SPEED_CNT = 'speed_cnt'

