uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO22
  tx_pin: GPIO19

external_components:
  - source: github://eigger/espcomponents/@latest
    components: [ uartex ]
    refresh: always  

uartex:
  rx_timeout: 10ms
  tx_delay: 50ms
  tx_timeout: 500ms
  tx_retry_cnt: 3

  rx_header: [0xAA, 0x55]
  rx_footer: [0x0D, 0x0D]
  tx_header: [0xAA, 0x55]
  tx_footer: [0x0D, 0x0D]

  rx_checksum: add_no_header
  tx_checksum: add_no_header

  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

light:
  #Room0
  - platform: uartex
    name: "Room 0 Light 1"
    id: room_0_light_1
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_0_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_0_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    #command_state: [0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    #update_interval: 300s

  - platform: uartex
    name: "Room 0 Light 2"
    id: room_0_light_2
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_0_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_0_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  #Room1
  - platform: uartex
    name: "Room 1 Light 1"
    id: room_1_light_1
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x01]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_1_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_1_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  - platform: uartex
    name: "Room 1 Light 2"
    id: room_1_light_2
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x01]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_1_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_1_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x01, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  #Room2
  - platform: uartex
    name: "Room 2 Light 1"
    id: room_2_light_1
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x02]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_2_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_2_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  - platform: uartex
    name: "Room 2 Light 2"
    id: room_2_light_2
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x02]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_2_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_2_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x02, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  #Room3
  - platform: uartex
    name: "Room 3 Light 1"
    id: room_3_light_1
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x03]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light2 = id(room_3_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, 0xff, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light2 = id(room_3_light_2).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, 0x00, light2, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

  - platform: uartex
    name: "Room 3 Light 2"
    id: room_3_light_2
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x03]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(room_3_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, light1, 0xff, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};
    command_off: !lambda |-
      uint8_t light1 = id(room_3_light_1).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x03, 0x01, 0x00, 0x00, light1, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc}};

#Heater
#8 -> power on: 0x11(hot water: 0x12), power off: 0x01(hot water: 0x02)
#9 -> away: 0x01, None: 0x00
#10 -> target temp
#11 -> hot water temp
#12 -> current temp
#13 -> heater water temp
#14 -> error code
#15 -> boiler error

#Aircon
#8 -> power on: 0x10, power off: 0x00
#9 -> cool: 0x00, fan_only: 0x01, dry: 0x02, auto: 0x03
#10 -> fan off: 0x00, fan low: 0x01, fan medium: 0x02, fan high: 0x03
#11 -> current temp
#12 -> target temp
climate:
  #Room0
  - platform: uartex
    name: "Room 0 Heater"
    id: room_0_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x00]
      mask: [0xF0]
    state_heat:
      offset: 8
      data: [0x10]
      mask: [0xF0]
    command_off: !lambda |-
      float target = id(room_0_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_0_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    #command_state: [0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
    #update_interval: 300s

  #Room1
  - platform: uartex
    name: "Room 1 Heater"
    id: room_1_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x01]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    command_off: !lambda |- 
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};

  #Room2
  - platform: uartex
    name: "Room 2 Heater"
    id: room_2_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x02]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    command_off: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};

  #Room3
  - platform: uartex
    name: "Room 3 Heater"
    id: room_3_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x03]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    command_off: !lambda |-
      float target = id(room_3_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_heat: !lambda |-
      float target = id(room_3_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};
    command_temperature: !lambda |-
      // @param: const float x
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc}};

valve:
  - platform: uartex
    name: "Gas Valve"
    state: 
      data: [0x30, 0xd0, 0x00, 0x2c, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_open:
      offset: 9
      data: [0xff]
    state_closed:
      offset: 9
      data: [0x00]
    command_close:
      data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc]

sensor:
  - platform: uartex
    name: "Elevator Floors"
    icon: "mdi:elevator"
    state: 
      data: [0x30, 0xd0, 0x00, 0x44, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_number:
      offset: 9
      length: 1
      precision: 0

button:
  - platform: uartex
    name: "Elevator Call"
    icon: "mdi:elevator"
    command_on: 
      data: [0x30, 0xbc, 0x00, 0x44, 0x00, 0x01, 0x00, 0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]



# # Packet Structure Documentation

# ## Packet Structure

# ### Fields

# - **Head**
#   - Size: 2 bytes
#   - Description: Fixed value `0xAA, 0x55`

# - **Type**
#   - Size: 2 bytes
#   - Description: Type of packet
#   - Values:
#     - `0x30, 0xBC`: Send
#     - `0x30, 0xDC`: Receive

# - **Device**
#   - Size: 2 bytes
#   - Description: Device identifier
#   - Values:
#     - `0x00, 0x01`: Wallpad
#     - `0x00, 0x0E`: Light
#     - `0x00, 0x2C`: Gas
#     - `0x00, 0x33`: Door
#     - `0x00, 0x36`: Heater
#     - `0x00, 0x39`: Aircon
#     - `0x00, 0x3B`: Switch
#     - `0x00, 0x44`: Elevator
#     - `0x00, 0x48`: Fan
#     - `0x00, 0x60`: Motion

# - **Room**
#   - Size: 2 bytes
#   - Description: Room identifier
#   - Values:
#     - `0x00, 0x01`: Livingroom
#     - `0x01, 0x01`: Room1
#     - `0x02, 0x01`: Room2
#     - `0x03, 0x01`: Room3

# - **Command**
#   - Size: 2 bytes
#   - Description: Command to execute
#   - Values:
#     - `0x00, 0x00`: Common
#     - `0x00, 0x01`: Elevator
#     - `0x00, 0x02`: Gas
#     - `0x00, 0x04`: Motion
#     - `0x00, 0x3A`: Scan
#     - `0x00, 0x98`: Sensor

# - **Payload**
#   - Size: 8 bytes
#   - Description: Data or additional information
#   - Structure:
#     - **Heater:**
#       - Byte 0: Power state
#         - `0x11`: Power on
#         - `0x01`: Power off
#       - Byte 1: Mode
#         - `0x01`: Away
#         - `0x00`: None
#       - Byte 2: Target temperature
#       - Byte 3: Hot water temperature
#       - Byte 4: Current temperature
#       - Byte 5: Heater water temperature
#       - Byte 6: Error code
#       - Byte 7: Boiler error
#     - **Aircon:**
#       - Byte 0: Power state
#         - `0x10`: Power on
#         - `0x00`: Power off
#       - Byte 1: Mode
#         - `0x00`: Cool
#         - `0x01`: Fan only
#         - `0x02`: Dry
#         - `0x03`: Auto
#       - Byte 2: Fan speed
#         - `0x00`: Fan off
#         - `0x01`: Fan low
#         - `0x02`: Fan medium
#         - `0x03`: Fan high
#       - Byte 3: Current temperature
#       - Byte 4: Target temperature
#     - **Light & Switch:**
#       - Byte 0: Light/Switch 1 state
#         - `0xFF`: On
#         - `0x00`: Off
#       - Byte 1: Light/Switch 2 state
#         - `0xFF`: On
#         - `0x00`: Off
#       - Byte 2: Light/Switch 3 state
#         - `0xFF`: On
#         - `0x00`: Off
#     - **Fan:**
#       - Byte 0: Onoff (CO2, 0x01)
#         - `0x10`: On
#         - `0x00`: Off
#       - Byte 1: Fan mode
#         - `0x00`: None
#         - `0x01`: vent
#         - `0x02`: auto
#         - `0x03`: bypass
#         - `0x05`: night
#         - `0x08`: purifier
#       - Byte 2: Fan Speed
#         - `0x00`: Off
#         - `0x40`: Low
#         - `0x80`: Medium
#         - `0xC0`: High
#       - Byte 3, 4: Co2 value
#       - Byte 5: Error Code
#     - **Sensor:**
#       - Byte 0: PM10
#       - Byte 1: PM2.5
#       - Byte 2, 3: Co2
#       - Byte 4, 5: Voc
#       - Byte 5: Temperature
#       - Byte 6: Humidity
#     - **Gas:**
#       - None
#     - **Elevator:**
#       - Byte 0: Direction
#         - `0x00`: None
#         - `0x01`: Down
#         - `0x02`: Up
#         - `0x03`: Arrival
#       - Byte 1: floor

# - **Checksum**
#   - Size: 1 byte
#   - Description: Validates data integrity
#   - Calculation: Sum of all field values modulo 256

# - **Footer**
#   - Size: 2 bytes
#   - Description: Fixed value `0x0D, 0x0D`

# ## Examples

# ### Send Packet Example
# Head: 0xAA, 0x55
# Type: 0x30, 0xBC
# Device: 0x00, 0x39 (Aircon)
# Room: 0x00, 0x01 (Livingroom)
# Command: 0x00, 0x98 (Sensor)
# Payload: 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08
# Checksum: <sum of all fields modulo 256>
# Footer: 0x0D, 0x0D

# ### Receive Packet Example
# Head: 0xAA, 0x55
# Type: 0x30, 0xDC
# Device: 0x00, 0x2C (Gas)
# Room: 0x01, 0x01 (Room1)
# Command: 0x00, 0x02 (Gas)
# Payload: 0x0A, 0x0B, 0x0C, 0x0D, 0x0E, 0x0F, 0x10, 0x11
# Checksum: <sum of all fields modulo 256>
# Footer: 0x0D, 0x0D



