uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO22
  tx_pin: GPIO19

external_components:
  - source: github://eigger/espcomponents@latest
    components: [ uartex ]
    refresh: always  

uartex:
  rx_timeout: 10ms
  rx_length: 21
  tx_delay: 100ms
  tx_timeout: 500ms
  tx_retry_cnt: 3

  rx_header: [0xAA, 0x55]
  rx_footer: [0x0D, 0x0D]
  tx_header: [0xAA, 0x55]
  tx_footer: [0x0D, 0x0D]

  rx_checksum: add_no_header
  tx_checksum: add_no_header

  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

light:
  #Room0
  - platform: uartex
    name: "Livingroom Light 1"
    id: livingroom_light_1
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 8
      data: [0xff]
    state_off:
      offset: 8
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = 0xff;
      uint8_t light2 = id(livingroom_light_2).current_values.is_on() ? 0xff : 0x00;
      uint8_t light3 = id(livingroom_light_3).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, light2, light3, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc, 0x00, 0x0e, 0x00}};
    command_off: !lambda |-
      uint8_t light1 = 0x00;
      uint8_t light2 = id(livingroom_light_2).current_values.is_on() ? 0xff : 0x00;
      uint8_t light3 = id(livingroom_light_3).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, light2, light3, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc, 0x00, 0x0e, 0x00}};
    command_update: 
      data: [0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x0e, 0x00]
    update_interval: 2h

  - platform: uartex
    name: "Livingroom Light 2"
    id: livingroom_light_2
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 9
      data: [0xff]
    state_off:
      offset: 9
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(livingroom_light_1).current_values.is_on() ? 0xff : 0x00;
      uint8_t light2 = 0xff;
      uint8_t light3 = id(livingroom_light_3).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, light2, light3, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc, 0x00, 0x0e, 0x00}};
    command_off: !lambda |-
      uint8_t light1 = id(livingroom_light_1).current_values.is_on() ? 0xff : 0x00;
      uint8_t light2 = 0x00;
      uint8_t light3 = id(livingroom_light_3).current_values.is_on() ? 0xff : 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, light2, light3, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc, 0x00, 0x0e, 0x00}};

  - platform: uartex
    name: "Livingroom Light 3"
    id: livingroom_light_3
    state: 
      data: [0x30, 0xd0, 0x00, 0x0e, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_on:
      offset: 10
      data: [0xff]
    state_off:
      offset: 10
      data: [0x00]
    command_on: !lambda |-
      uint8_t light1 = id(livingroom_light_1).current_values.is_on() ? 0xff : 0x00;
      uint8_t light2 = id(livingroom_light_2).current_values.is_on() ? 0xff : 0x00;
      uint8_t light3 = 0xff;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, light2, light3, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc, 0x00, 0x0e, 0x00}};
    command_off: !lambda |-
      uint8_t light1 = id(livingroom_light_1).current_values.is_on() ? 0xff : 0x00;
      uint8_t light2 = id(livingroom_light_2).current_values.is_on() ? 0xff : 0x00;
      uint8_t light3 = 0x00;
      return {{0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x00, light1, light2, light3, 0x00, 0x00, 0x00, 0x00, 0x00}, {0x30, 0xdc, 0x00, 0x0e, 0x00}};

#Heater
#8 -> power on: 0x11(hot water: 0x12), power off: 0x01(hot water: 0x02)
#9 -> away: 0x01, None: 0x00
#10 -> target temp
#11 -> hot water temp
#12 -> current temp
#13 -> heater water temp
#14 -> error code
#15 -> boiler error

#Aircon
#8 -> power on: 0x10, power off: 0x00
#9 -> cool: 0x00, fan_only: 0x01, dry: 0x02, auto: 0x03
#10 -> fan off: 0x00, fan low: 0x01, fan medium: 0x02, fan high: 0x03
#11 -> current temp
#12 -> target temp
climate:
  #Room0
  - platform: uartex
    name: "Livingroom Heater"
    id: livingroom_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
    state_temperature_target:
      offset: 10
    state_off:
      offset: 8
      data: [0x00]
      mask: [0xF0]
    state_heat:
      offset: 8
      data: [0x10]
      mask: [0xF0]
    state_preset_away:
      offset: 9
      data: [0x01]
    state_preset_none:
      offset: 9
      data: [0x00]
    command_off: !lambda |-
      float target = id(livingroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x00}};
    command_heat: !lambda |-
      float target = id(livingroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x00}};
    command_preset_none: !lambda |-
      float target = id(livingroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x00}};
    command_preset_away: !lambda |-
      float target = id(livingroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x01, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x00}};
    command_temperature: !lambda |-
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x00}};
    command_update: 
      data: [0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x36, 0x00]
    update_interval: 2h

  #Room1
  - platform: uartex
    name: "Bedroom Heater"
    id: bedroom_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x01]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
      length: 1
      precision: 0
    state_temperature_target:
      offset: 10
      length: 1
      precision: 0
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    state_preset_away:
      offset: 9
      data: [0x01]
    state_preset_none:
      offset: 9
      data: [0x00]
    command_off: !lambda |- 
      float target = id(bedroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x01}};
    command_heat: !lambda |-
      float target = id(bedroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x01}};
    command_preset_none: !lambda |-
      float target = id(bedroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x01}};
    command_preset_away: !lambda |-
      float target = id(bedroom_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x01, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x01}};
    command_temperature: !lambda |-
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x01}};
    command_update: 
      data: [0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x36, 0x01]
    update_interval: 2h

  #Room2
  - platform: uartex
    name: "Room 1 Heater"
    id: room_1_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x02]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
    state_temperature_target:
      offset: 10
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    state_preset_away:
      offset: 9
      data: [0x01]
    state_preset_none:
      offset: 9
      data: [0x00]
    command_off: !lambda |-
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x02}};
    command_heat: !lambda |-
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x02}};
    command_preset_none: !lambda |-
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x02}};
    command_preset_away: !lambda |-
      float target = id(room_1_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x01, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x02}};
    command_temperature: !lambda |-
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x02}};
    command_update: 
      data: [0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x36, 0x02]
    update_interval: 2h

  #Room3
  - platform: uartex
    name: "Room 2 Heater"
    id: room_2_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x03]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
    state_temperature_target:
      offset: 10
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    state_preset_away:
      offset: 9
      data: [0x01]
    state_preset_none:
      offset: 9
      data: [0x00]
    command_off: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x03}};
    command_heat: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x03}};
    command_preset_none: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x03}};
    command_preset_away: !lambda |-
      float target = id(room_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x01, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x03}};
    command_temperature: !lambda |-
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x03}};
    command_update: 
      data: [0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x36, 0x03]
    update_interval: 2h

  #Room4
  - platform: uartex
    name: "Livingroom 2 Heater"
    id: livingroom_2_heater
    visual:
      min_temperature: 5 °C
      max_temperature: 30 °C
      temperature_step: 1 °C
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x04]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_temperature_current:
      offset: 12
    state_temperature_target:
      offset: 10
    state_off:
      offset: 8
      data: [0x01]
    state_heat:
      offset: 8
      data: [0x11]
    state_preset_away:
      offset: 9
      data: [0x01]
    state_preset_none:
      offset: 9
      data: [0x00]
    command_off: !lambda |-
      float target = id(livingroom_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x01, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x04}};
    command_heat: !lambda |-
      float target = id(livingroom_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x04}};
    command_preset_none: !lambda |-
      float target = id(livingroom_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x04}};
    command_preset_away: !lambda |-
      float target = id(livingroom_2_heater).target_temperature;
      return {{0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x01, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x04}};
    command_temperature: !lambda |-
      float target = x;
      return {{0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x00, 0x11, 0x00, (uint8_t)target, 0x00, 0x00, 0x00, 0x00, 0x00},{0x30, 0xdc, 0x00, 0x36, 0x04}};
    command_update: 
      data: [0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x36, 0x04]
    update_interval: 2h

sensor:
  - platform: uartex
    name: "Livingroom Temperature"
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    state_number:
      offset: 12
  - platform: uartex
    name: "Bedroom Temperature"
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x01]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    state_number:
      offset: 12
  - platform: uartex
    name: "Room 1 Temperature"
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x02]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    state_number:
      offset: 12
  - platform: uartex
    name: "Room 2 Temperature"
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x03]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    state_number:
      offset: 12
  - platform: uartex
    name: "Livingroom 2 Temperature"
    state: 
      data: [0x30, 0xd0, 0x00, 0x36, 0x04]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    unit_of_measurement: "°C"
    icon: "mdi:thermometer"
    device_class: "temperature"
    state_class: "measurement"
    state_number:
      offset: 12

#OFF <AA 55 30 BC 00 01 00 2C 00 02 00 00 00 00 00 00 00 00 1B 0D 0D 
#OFF  AA 55 30 DC 00 2C 00 01 00 02 00 00 00 00 00 00 00 00 3B 0D 0D
#ON  <AA 55 30 BC 00 01 00 2C 00 01 00 00 00 00 00 00 00 00 1A 0D 0D 
#     AA 55 30 DC 00 2C 00 01 00 01 00 00 00 00 00 00 00 00 3A 0D 0D
# valve:
#   - platform: uartex
#     name: "Gas Valve"
#     state: 
#       data: [0x30, 0xd0, 0x00, 0x2c, 0x00]
#       mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
#     state_open:
#       offset: 7
#       data: [0x01]
#     state_closed:
#       offset: 7
#       data: [0x02]
#     command_close:
#       data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
#       ack: [0x30, 0xdc]
#     command_update: 
#       data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
#       ack: [0x30, 0xdc]
#     update_interval: 2h
lock:
  - platform: uartex
    name: "Gas Buner Lock"
    icon: mdi:gas-burner
    state: 
      data: [0x30, 0xd0, 0x00, 0x2c, 0x00]
      mask: [0xff, 0xf0, 0xff, 0xff, 0xff]
    state_unlocked:
      offset: 7
      data: [0x01]
    state_locked:
      offset: 7
      data: [0x02]
    command_lock:
      data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x02, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x2c, 0x00]
    command_update: 
      data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc, 0x00, 0x2c, 0x00]
    update_interval: 2h

text_sensor:
  - platform: uartex
    name: "Elevator"
    icon: "mdi:elevator"
    state: 
      data: [0x30, 0x00, 0x00, 0x01, 0x00, 0x44, 0x00]
      mask: [0xff, 0x00, 0xff, 0xff, 0xff, 0xff, 0xff]
    lambda: |-
      if (check_value(8, 0x00, data, len)) return "호출";
      if (check_value(8, 0x03, data, len)) return "도착";
      return "Unknown";

# AA 55 30 BC 00 01 00 44 00 01 03 00 00 00 00 00 00 00 35 0D 0D
button:
  - platform: uartex
    name: "Elevator Call"
    icon: "mdi:elevator"
    command_on: 
      data: [0x30, 0xbc, 0x00, 0x01, 0x00, 0x44, 0x00, 0x01, 0x03, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
      ack: [0x30, 0xdc]

  # - platform: template
  #   name: "Refresh"
  #   icon: "mdi:refresh-circle"
  #   on_press:
  #     #Valve
  #     - uartex.write: 
  #         data: [0x30, 0xbc, 0x00, 0x2c, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  #         ack: [0x30, 0xdc]
  #     #Light
  #     - uartex.write: 
  #         data: [0x30, 0xbc, 0x00, 0x0e, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  #         ack: [0x30, 0xdc]
  #     #Heater
  #     - uartex.write: 
  #         data: [0x30, 0xbc, 0x00, 0x36, 0x00, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  #         ack: [0x30, 0xdc]
  #     - uartex.write: 
  #         data: [0x30, 0xbc, 0x00, 0x36, 0x01, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  #         ack: [0x30, 0xdc]
  #     - uartex.write: 
  #         data: [0x30, 0xbc, 0x00, 0x36, 0x02, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  #         ack: [0x30, 0xdc]
  #     - uartex.write: 
  #         data: [0x30, 0xbc, 0x00, 0x36, 0x03, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  #         ack: [0x30, 0xdc]
  #     - uartex.write: 
  #         data: [0x30, 0xbc, 0x00, 0x36, 0x04, 0x01, 0x00, 0x3a, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00]
  #         ack: [0x30, 0xdc]