uart:
  baud_rate: 9600
  data_bits: 8
  parity: NONE
  stop_bits: 1
  rx_pin: GPIO22
  tx_pin: GPIO19

external_components:
  - source: github://eigger/espcomponents@latest
    components: [ uartex ]
    refresh: always

uartex:
  rx_timeout: 10ms
  rx_length: 21
  tx_delay: 500ms
  tx_timeout: 1s
  tx_retry_cnt: 3

  rx_header: [0xAA, 0x55]
  rx_footer: [0x0D, 0x0D]
  tx_header: [0xAA, 0x55]
  tx_footer: [0x0D, 0x0D]

  rx_checksum: add_no_header
  tx_checksum: add_no_header

  rx_priority: loop

  version:
    disabled: False
  error:
    disabled: False
  log:
    disabled: False

esphome:
  areas:
    - id: area_livingroom
      name: ""
    - id: area_bedroom
      name: ""
    - id: area_room_1
      name: ""
    - id: area_room_2
      name: ""
    - id: area_kitchen
      name: ""
    - id: area_entrance
      name: ""

  devices:
    - id: device_livingroom
      area_id: area_livingroom
      name: "${friendly_name} Livingroom"
    - id: device_bedroom
      area_id: area_bedroom
      name: "${friendly_name} Bedroom"
    - id: device_room_1
      area_id: area_room_1
      name: "${friendly_name} Room 1"
    - id: device_room_2
      area_id: area_room_2
      name: "${friendly_name} Room 2"
    - id: device_kitchen
      area_id: area_kitchen
      name: "${friendly_name} Kitchen"
    - id: device_entrance
      area_id: area_entrance
      name: "${friendly_name} Entrance"

packages:
  livingroom: !include
    file: fragments/room.yaml
    vars:
      room_num: 0
      name_prefix: "Livingroom"
      device_id: device_livingroom
      light_count: 3
      aircon: 0
  bedroom: !include
    file: fragments/room.yaml
    vars:
      room_num: 1
      name_prefix: "Bedroom"
      device_id: device_bedroom
      light_count: 0
      aircon: 0
  room_1: !include
    file: fragments/room.yaml
    vars:
      room_num: 2
      name_prefix: "Room 1"
      device_id: device_room_1
      light_count: 0
      aircon: 0
  room_2: !include
    file: fragments/room.yaml
    vars:
      room_num: 3
      name_prefix: "Room 2"
      device_id: device_room_2
      light_count: 0
      aircon: 0
  livingroom_2: !include
    file: fragments/room.yaml
    vars:
      room_num: 4
      name_prefix: "Livingroom 2"
      device_id: device_livingroom
      light_count: 0
      aircon: 0
  gas: !include
    file: fragments/gas_package.yaml
    vars:
      device_id: device_kitchen
  elevator: !include
    file: fragments/elevator.yaml
    vars:
      device_id: device_entrance
